#+title: Games
#+author: pspiagicw

* Games
** 2D
*** Shop Empire Series
    This series is one of the games I have played with Gautam. This series involves managing a shopping industry spread across multiple continents.
    It's series adds multiple new features and even cool new locations (Fable , Ancient Greece) and expand upon the base formula.
    There is even a anti-shop empire game , where you work as a robber to bankrupt the mall chain!
*** Earn to Die
    Also one of the games I played with Gautam. This is a classic and involves ploughing your vehicle through hordes of zombies.
    We upgrade our vehicles and even change them , ultimately we reach the goal wherever we want to reach!
*** Air Traffic Management Series
    I was excited to play this game in peace , required ultimate concentration and control over the situation.
    Simply you had to manage a airport!
*** New York Taxi
    I loved this game, this game was relaxing.Nidu , Sidu were irritated that I always played this.
    But one of the most simple map , simple missions and smooth controls.
*** Firegirl and Waterboy
    My brothers have played this for so much time. I enjoyed at first but I hated the puzzles.
*** Oxygen Not Included
*** Stardew Valley
*** Big Head Football 2
*** Prison Architect
** 3D
*** Spiderman 3
    The very first 3d game I played . My father bought this game ?
    It ran very good on my then PC , I am really suprised by the fact now.
    Although I never finished , my brothers and myself came really close to beat it.
    We failed in the last Quick Time Events for killing Venom.
    Although the game got very poor ratings along with the movie. But we loved it!
    We played so much that mother wanted us to delete this game.She failed the first time , but second time she did not!
    Features:
    * Superb Combat and unique story different from the movie
    * Villains include Kraven the Hunter,Venom,Lizard,Kingpin,Green Goblin
*** Need for Speed Most Wanted
    After the deletion of Spiderman 3 , this was the second game I started playing.I got from my friend Rahul.
    He was very good with computers. One of the most played and iconic games ever. I also played the DLC version later.
    Has the most sexiest,fastest cars of the world. Superb Controls , I install this game on every computer I can play on ever.
    Completed this game more than 20 times.
*** MineCraft
    The iconic minecraft , also given by Rahul . Still going strong after so many years , this game cannot die.
    I introduced this game to the society.I still get invited to play multiplayer!
*** Assassin's Creed 1
    Downloaded on my birthday . First game I pirated on my own! Downloaded from Oceanofgames.Prayed that the internet that day would not
    stop. Wifi at that time (TP-LINK) was slow and we did not use it much unlike now
    I love the story and dystopian world the protaganist lived in.
    Although the game became repetitive , we played it till the end! Could not beat the boss (because of the lag!).
    It provided the experience to enjoy the story , how our teacher betrayed us in the end is cool.
    We also become arrogant and endure loss of our entire kingdom. The templar connection in modern world
    was the best double story. I am still intrigued by the modern one than the ancient one.
*** Assassin's Creed 2
    Saw the gameplay, downloaded the game. Best intro ever. The connection with the brothers and sisters , parents made us feel the death of our family.
    Kind of long story filled with multiple characters. The song /Ezio's Family/ will be the theme song of Assassin's Creed forever.Love this song.
    The story is cool and really expanded the universe. Lucy looks cute! Modern story well expanded.
    Ezio Auditore da Firenze is the best assassin's creed protagonist ever. The sacrifices and the hardships.
    The song shows that whatever you do , somethings always break or  never heal.
    The gameplay expanded a lot! Includes almost all the things that modern games has!.
    We get to meet Learnardo da Vinci.
*** Assassin's Creed 4
    Very emotional story , just a simple job turns Edwards Keyway's life over. His ideology with his wife is also well expanded.
    In the end , she still believes in us and entrusts our daughter with us.
    Shows the major players in Central America pirate days (Black Beard , Bonnie and Clyd etc).
    His son becomes the father to protaganist of Assassin's Creed 3.
    Good theme song. Very good gameplay with the ship and fighting with swords and gun simultaneously.
*** Far Cry 3
*** Far Cry 5
*** DOOM Eternal
*** Call of Duty Modern Warfare
*** Call of Duty Modern Warfare 2
*** Call of Duty 2
*** BattleField 2
*** Xonotic
*** GTA 5
*** Kerbal Space Program
*** Sleeping Dogs
*** Need For Speed Rivals
*** BMW GT3 Simulator
*** Microsoft Flight Simulator X
*** Microsoft Train Simulator
*** Just Cause 2
*** Just Cause 3
*** Modern Warfare 5
*** Asphalt 9
*** Project Cars 2
*** Age of Empires
*** Civilization 5
*** DOOM 3: BFG Edition
*** Metal Gear Solid 5
    
